### ISSUE TITLE
server_namer.txt where is plugin source?

### ISSUE THREAD

**Issue by Owned67** [mvandorp/server-plugins#1]
Hello,

server_namer.txt is found but where is source plugin?

Cheers

**Comment by mvandorp** [comment]
Hi Owned, you are right, the server_namer.txt is on this repo but the plugin itsself is not, oops.

The plugin and its source can be found here:
https://forums.alliedmods.net/showthread.php?p=2030557

**Comment by Owned67** [comment]
Hi,

yes i have found and mistake to close this ^^

Thanks
